# Default values for layer1_port_owncloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: zivgitlab.wwu.io
  repository: sciebo-rds/sciebo-rds/port_owncloud
  tag: v0.1-fix-ci
  pullPolicy: Always

labels:
  app.kubernetes.io/component: research-data-services.org
  app.kubernetes.io/part-of: connector
  research-data-services.org/layer: layer1

nameOverride: ""
fullnameOverride: layer1-port-owncloud

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
    prometheus.io/scrape: "true"

domain: localhost
ingress:
  tls:
    secretName: sciebords-tls-public

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Domains you want to use as input, currently only owncloud supported,
# overwrites layer1-port-owncloud environment and bootsup multiple pods
domains:
  - name: localhost
    ADDRESS: https://127.0.0.1
    OAUTH_CLIENT_ID: ""
    OAUTH_CLIENT_SECRET: ""

# uses namehost
environment: 
  ADDRESS: https://localhost
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""

