apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "layer0_describo.fullname" . }}
  labels:
{{ include "layer0_describo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "layer0_describo.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "layer0_describo.labels" . | indent 8 }}
    spec:
      volumes:
        - name: describo-configuration
          configMap:
            name: describo-configuration-file
            items:
            - key: configuration.json
              path: configuration.json
            - key: type-definitions-lookup.json
              path: type-definitions-lookup.json
            - key: type-definitions.json
              path: type-definitions.json
            - key: nginx.conf
              path: nginx.conf
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: "api"
          image: "{{ .Values.image.repository }}{{ .Values.image.api }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: describo-configuration
              mountPath: /srv/configuration.json
              subPath: configuration.json
              readOnly: true
            - name: describo-configuration
              mountPath: /srv/type-definitions-lookup.json
              subPath: type-definitions-lookup.json
              readOnly: true
            - name: describo-configuration
              mountPath: /srv/type-definitions.json
              subPath: type-definitions.json
              readOnly: true
          env:
          - name: "DB_HOST"
            value: {{ .Values.environment.DB_HOST | quote }}
          - name: "DB_PORT"
            value: {{ .Values.environment.DB_PORT | quote }}
          - name: "DB_USER"
            value: {{ .Values.environment.DB_USER | quote }}
          - name: "DB_PASSWORD"
            value: {{ .Values.environment.DB_PASSWORD | quote }}
          - name: "DB_DATABASE"
            value: {{ .Values.environment.DB_DATABASE | quote }}
          - name: "NODE_ENV"
            value: "production"
          - name: "LOG_LEVEL"
            value: {{ .Values.environment.LOG_LEVEL | quote}}
          envFrom:
          - configMapRef:
              name: mservice
          - configMapRef:
              name: proxy
          - configMapRef:
              name: globalenvvar
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: "ui"
          image: "{{ .Values.image.repository }}{{ .Values.image.ui }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: describo-configuration
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
          env:
          - name: "VUE_APP_BASE_URL"
            value: "{{ .Values.ingress.path }}"
          - name: "NODE_ENV"
            value: "production"
          envFrom:
          - configMapRef:
              name: mservice
          - configMapRef:
              name: proxy
          - configMapRef:
              name: globalenvvar
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
