{{- $fullName := include "layer0_web.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "layer0_web.labels" . | indent 4 }}
  annotations:
{{- include "common.ingressAnnotations" . |  nindent 4 }}
spec:
  {{- if (include "common.tlsSecretName" .) }}
  tls:
    - hosts:
        - {{ .Values.global.rds.domain }}
      secretName: {{ include "common.tlsSecretName" . }}
  {{- end }}
  rules:
    - host: {{ .Values.global.rds.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
