apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: circle1-port-openscienceframework
version: 0.2.3
home: https://www.research-data-services.org/
engine: gotpl
keywords:
- research
- data
- services
- openscienceframework
maintainers:
- email: peter.heiss@uni-muenster.de
  name: Heiss
details:
  This Helm chart provides a system to handle the research data in your cloud to push them to other services.
sources:
- https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png