apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
  name: {{ include "layer1_port_reva.fullname" . }}
  namespace: {{ .Release.Namespace  }}
  labels:
{{ include "layer1_port_reva.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "layer1_port_reva.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
