{{- $domains := .Values.domains -}}
{{- if .Values.global }}
    {{- if .Values.global.domains }}
        {{- $domains = .Values.global.domains -}}
    {{- end -}}
{{- end -}}

{{- if not $domains -}}
{{- $name := (dict "name" (.Values.environment.ADDRESS | replace "https://" "" | replace "http://" "")) -}}
{{- $domains = (list (merge .Values.environment $name)) -}}
{{- end -}}

{{- range $domains }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portowncloudconfig-{{ .name | replace "." "-" | replace ":" "-" }}
  namespace: {{ $.Values.global.namespace.name | default $.Release.Namespace  }}
data:
  OWNCLOUD_OAUTH_CLIENT_ID: {{ .OAUTH_CLIENT_ID | quote }}
  OWNCLOUD_INSTALLATION_URL: {{ .ADDRESS | quote }}
  OWNCLOUD_OAUTH_CLIENT_SECRET: {{ .OAUTH_CLIENT_SECRET | quote }}
  SERVICENAME: {{ .name | replace "." "-" | replace ":" "-" }}
{{- end }}