apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: layer0-describo
version: 0.2.8
home: https://www.research-data-services.org/
type: application
keywords:
  - research
  - data
  - services
  - describo
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
sources:
  - https://github.com/Sciebo-RDS/Sciebo-RDS
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: postgresql
    version: 10.14.3
    repository: file://../postgresql
    tags:
      - storage
  - name: common
    version: ^0.1.0
    repository: file://../common