apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: layer0-describo
version: 0.1.27
home: https://www.research-data-services.org/
engine: gotpl
keywords:
  - research
  - data
  - services
  - describo
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
details: This Helm chart provides a system to handle the research data in your cloud to push them to other services.
sources:
  - https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png
