apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: layer0-helper-describo-token-updater
version: 0.2.0
home: https://www.research-data-services.org/
type: application
keywords:
  - research
  - data
  - services
  - describo
  - describo-online
  - updater
  - layer3-token-storage
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
sources:
  - https://github.com/Sciebo-RDS/Sciebo-RDS
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: common
    version: ^0.1.0
    repository: file://../common
