apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: layer0-web
version: 0.2.1
home: https://www.research-data-services.org/
keywords:
  - research
  - data
  - services
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
sources:
  - https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: common
    version: ^0.1.0
    repository: file://../common
