# Default values for circle3_token_storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: zivgitlab.wwu.io/sciebo-rds/rds-web/rds_web
  tag: latest
  pullPolicy: Always

labels:
  app.kubernetes.io/component: research-data-services.org
  app.kubernetes.io/part-of: rds-ingress
  research-data-services.org/layer: layer0

fullnameOverride: layer0-web

global:
  domain: localhost
  ingress:
    tls:
      secretName: sciebords-tls-public

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"

domain: localhost
ingress:
  path: /
  tls:
    secretName: sciebords-tls-public
  annotations:
    kubernetes.io/ingress.class: nginx-internal
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  EMBED_MODE: true
  FLASK_ORIGINS:
    [
      "http://localhost:8080",
      "http://localhost:8085",
      "http://localhost:8000",
      "http://localhost:9100",
      "https://<your-rds-installation>",
    ]
  SECRET_KEY: 1234
  OWNCLOUD_URL: http://localhost:8000
  OWNCLOUD_OAUTH_CLIENT_ID: ABC
  OWNCLOUD_OAUTH_CLIENT_SECRET: XYZ
  OWNCLOUD_OAUTH_CLIENT_REDIRECT: https://<your-rds-installation>
  OWNCLOUD_OAUTH_CLIENT_AUTHORIZE_URL: http://localhost:8000/apps/oauth2/authorize
  DESCRIBO_API_ENDPOINT: http://localhost:9000/api/session/application
  DESCRIBO_API_SECRET: IAMSECRET
  VUE_APP_DESCRIBO_URL: https://<your-rds-installation>/describo/application
  VUE_APP_FRONTENDHOST: https://<your-rds-installation>
  VUE_APP_SOCKETIO_HOST: https://<your-rds-installation>
  SOCKETIO_HOST: https://sciebords.uni-muenster.de
  SOCKETIO_PATH: /socket.io
  VUE_APP_BASE_URL: /
