# Default values for layer3_token_storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: zivgitlab.wwu.io
  repository: sciebo-rds/sciebo-rds/rds_web
  tag: release
  pullPolicy: Always

labels:
  app.kubernetes.io/component: research-data-services.org
  app.kubernetes.io/part-of: rds-ingress
  research-data-services.org/layer: layer0

fullnameOverride: layer0-web

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"

ingress:
  path: /
  annotations:
    nginx.org/server-snippets: |
      location /socket.io/ {
          proxy_http_version 1.1;
          proxy_redirect off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header        Host                    $host;
          proxy_set_header        X-Real-IP               $remote_addr;
          proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
          proxy_pass http://layer0-web/socket.io/;
      }
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  EMBED_MODE: true
  FLASK_ORIGINS:
    - "http://localhost:8080"
    - "http://localhost:8085"
    - "http://localhost:8000"
    - "http://localhost:9100"
  SECRET_KEY: 1234
  DESCRIBO_API_ENDPOINT: http://layer0-describo/api/session/application
  #SOCKETIO_HOST: https://<your-rds-installation>
  SOCKETIO_PATH: /socket.io/
  VUE_APP_BASE_URL: /

global:
  rds:
    domain: hey
  describo:
    domain: hej
    api_secret: asd

#   domains:
#   - name: owncloud.local # have to be equal to the second part of cloudID in owncloud
#     ADDRESS: https://owncloud.local/owncloud
#     OAUTH_CLIENT_ID: ABC
#     OAUTH_CLIENT_SECRET: XYZ
#     # filter settings for services for this domain. This is very usable, if you want to connect a single RDS instance to multiple installations.
#     # So you can show some specific services only for some ownclouds and show other services to others. Domainname in only and except have to be the same as in domains
#     filters:
#       # example!
#       only: # only this services will be shown to users of this domain
#       - "layer1-port-zenodo"
#       except: # all other services will be shown to users of this domain
#       - "layer1-port-openscienceframework"
#       # if only and except are used at the same time, the system will filter for only first and then for except. So except should be a subset of only, otherwise it is doing nothing.
