.use_case_port_service:
  variables:
    FOLDER: RDS/circle2_use_cases/port

.tests_use_case_port_service:
  extends:
    - .tests
    - .use_case_port_service

test:use_case_port_service3.8:
  image: zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers//python:3.8
  extends: .tests_use_case_port_service

build:use_case_port_service:
  needs:
    - test:use_case_port_service3.8

  extends:
    - .builds
    - .use_case_port_service

  only:
    changes:
      - RDS/circle2_use_cases/port/*
      - RDS/circle2_use_cases/port/**/*

doc:use_case_port_service:
  image: zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers//python:3.8
  needs:
    - build:use_case_port_service
  extends:
    - .documentation
    - .use_case_port_service
