apiVersion: v2
appVersion: "1.0"
description: A single chart for installing whole sciebo rds ecosystem.
name: all
version: 0.2.10
home: https://www.research-data-services.org/
type: application
keywords:
  - research
  - data
  - services
  - zenodo
maintainers:
  - email: peter.heiss@uni-muenster.de
    name: Heiss
sources:
  - https://github.com/Sciebo-RDS/Sciebo-RDS
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: layer0-describo
    version: ^0.2.0
    repository: file://../layer0_describo
    condition: layer0-describo.enabled
    tags:
      - layer0
  - name: layer0-web
    version: ^0.3.0
    repository: file://../layer0_web
    condition: layer0-web.enabled
    tags:
      - layer0
  - name: layer0-helper-describo-token-updater
    version: ^0.2.0
    repository: file://../layer0_helper_describo_token_updater
    condition: feature.redis
    tags:
      - layer0
  - name: layer1-port-openscienceframework
    version: ^0.2.0
    repository: file://../layer1_port_openscienceframework
    condition: layer1-port-openscienceframework.enabled
    tags:
      - layer1
  - name: layer1-port-zenodo
    version: ^0.2.0
    repository: file://../layer1_port_zenodo
    condition: layer1-port-zenodo.enabled
    tags:
      - layer1
  - name: layer1-port-owncloud
    version: ^0.3.0
    repository: file://../layer1_port_owncloud
    condition: layer1-port-owncloud.enabled
    tags:
      - layer1
  - name: layer1-port-reva
    version: ^0.2.0
    repository: file://../layer1_port_reva
    condition: layer1-port-reva.enabled
    tags:
      - layer1
  - name: layer2-exporter-service
    version: ^0.2.0
    repository: file://../layer2_exporter_service
    tags:
      - layer2
  - name: layer2-port-service
    version: ^0.2.0
    repository: file://../layer2_port_service
    tags:
      - layer2
  - name: layer2-metadata-service
    version: ^0.2.0
    repository: file://../layer2_metadata_service
    tags:
      - layer2
  - name: layer3-token-storage
    version: ^0.3.0
    repository: file://../layer3_token_storage
    tags:
      - layer3
  - name: layer3-research-manager
    version: ^0.3.0
    repository: file://../layer3_research_manager
    tags:
      - layer3
  - name: jaeger
    version: ^0.34.0
    repository: file://../jaeger
    condition: feature.jaeger
    tags:
      - monitoring
  - name: redis-cluster
    alias: redis
    version: ^7.6.1
    repository: file://../redis-cluster
    condition: feature.redis
    tags:
      - storage
  - name: redis
    alias: redis-helper
    version: ^16.10.1
    repository: file://../redis
    condition: feature.redis
    tags:
      - storage
