global:
  domain: localhost
  image:
    tag: v0.1.9
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_HELPER_HOST: redis-helper
  REDIS_HELPER_PORT: 6379
  REDIS_CHANNEL: TokenStorage_Refresh_Token

  # the external URL of the RDS service and describo
  # vue.js does not like running outside / of a webserver as it seems
  # so we have to run each service on its own single domain (so far)
  rds:
    domain: https://rds.example.com
  describo:
    domain: https://describo.example.com
    api_secret: secretstuff
# Set this to DEBUG and restart your applications to get more informations in logs. Default: INFO
loglevel: DEBUG
# If you set this to "False", SSL will not be verified in all https requests. Default: "True"
verify_ssl: "True"
# The URL, which you configured in your oauth providers
rds_oauth_redirect_uri: https://owncloud.local/index.php/apps/rds/oauth
proxy:
  http_proxy: "" # empty field
  https_proxy: "" # empty field
  no_proxy: "*"
namespace:
  create: false
  name: "research-data-services"
feature:
  jaeger: false
  redis: true
layer0-web:
  enabled: true
  environment:
    EMBED_MODE: true
    DESCRIBO_API_ENDPOINT: http://layer0-describo/api/session/application
layer0-describo:
  enabled: true
  postgresql:
    postgresqlDatabase: "describo"
    postgresqlUsername: "d9oNHWc41tVUIR4778Qsgi9kmi6c5FD2" # placeholder for security
    postgresqlPassword: "9hMh0QMKfpRTNWkktwPReyLWJkt9bDmE" # same as above
    persistence:
      size: 1Gi
layer0-helper-describo-token-updater:
  enabled: true
  environment:
    DESCRIBO_API_ENDPOINT: http://layer0-describo/api/session/application
layer1-port-zenodo:
  enabled: false
layer1-port-owncloud:
  enabled: false
layer1-port-openscienceframework:
  enabled: false
layer1-port-reva:
  enabled: false
layer2-exporter-service: {}
layer2-port-service: {}
layer2-metadata-service: {}
layer3-token-storage: {}
layer3-research-manager: {}
jaeger:
  ## All jaeger options: https://github.com/jaegertracing/helm-charts
  fullnameOverride: jaeger
  schema:
    activeDeadlineSeconds: 600
redis:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
  fullnameOverride: redis
  usePassword: false
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
redis-helper:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis
  fullnameOverride: redis-helper
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
  replica:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
postgresql:
  image:
    tag: 10.8.0
  service:
    port: "5432"
  fullnameOverride: postgresql
  postgresqlDatabase: "describo"
  postgresqlUsername: "admin"
  postgresqlPassword: "admin"
  persistence:
    enabled: true
    size: 1Gi
